import { getDb } from "./db";
import { getAllPriorities, getDashboard, predictReboot, getCvesForPatch } from "./engine";
import type { Patch, Server } from "./types";

interface PlanContent {
  kbs: string[];
  rings: { name: string; serverIds: string[]; window: string }[];
  rationale: string;
  rationaleModel: string;
}

export function generateComplianceReport(): { title: string; content: string } {
  const db = getDb();
  const dash = getDashboard();
  const servers = db.prepare("SELECT * FROM servers ORDER BY criticality DESC, name").all() as Server[];
  const priorities = getAllPriorities();
  const date = new Date().toISOString().slice(0, 10);

  const lines: string[] = [
    `# Patch Compliance Report — ${date}`,
    "",
    `Generated by PatchGPT. Fleet: ${dash.totalServers} servers, ${dash.compliancePct}% fully patched.`,
    "",
    "## Executive summary",
    "",
    `- **${dash.totalServers - dash.compliantServers} of ${dash.totalServers} servers** are missing at least one update.`,
    `- **${dash.exploitedExposure} servers** are exposed to at least one vulnerability that is being actively exploited in the wild.`,
    `- **${dash.pendingReboots} servers** have a pending reboot outstanding.`,
    "",
    "## Missing updates by priority",
    "",
    "| Priority | KB | Title | Score | Servers missing |",
    "|---|---|---|---|---|",
  ];
  for (const p of priorities.filter((x) => x.affectedServers.length > 0)) {
    const patch = db.prepare("SELECT title FROM patches WHERE kb = ?").get(p.kb) as { title: string };
    lines.push(`| ${p.tier} | ${p.kb} | ${patch.title} | ${p.score}/100 | ${p.affectedServers.length} |`);
  }

  lines.push("", "## Per-server status", "", "| Server | Role | Env | Criticality | Missing | Pending reboot | Last scan |", "|---|---|---|---|---|---|---|");
  for (const s of servers) {
    const missing = db
      .prepare("SELECT COUNT(*) AS n FROM server_patches WHERE server_id = ? AND status = 'missing'")
      .get(s.id) as { n: number };
    lines.push(
      `| ${s.name} | ${s.role} | ${s.environment} | ${s.criticality}/5 | ${missing.n} | ${s.pending_reboot ? "yes" : "no"} | ${s.last_scan?.slice(0, 16).replace("T", " ") ?? "never"} |`
    );
  }

  lines.push("", "## Environment compliance", "");
  for (const e of dash.envCompliance) {
    lines.push(`- **${e.environment}**: ${e.compliant}/${e.total} servers fully patched`);
  }

  return { title: `Compliance report ${date}`, content: lines.join("\n") };
}

export function generateDeploymentReport(planId: number): { title: string; content: string } {
  const db = getDb();
  const plan = db.prepare("SELECT * FROM plans WHERE id = ?").get(planId) as
    | { id: number; name: string; created_at: string; content: string }
    | undefined;
  if (!plan) throw new Error(`Plan ${planId} not found`);
  const content: PlanContent = JSON.parse(plan.content);
  const servers = db.prepare("SELECT * FROM servers").all() as Server[];
  const byId = new Map(servers.map((s) => [s.id, s]));

  const lines: string[] = [
    `# Deployment Report — ${plan.name}`,
    "",
    `Created ${plan.created_at.slice(0, 16).replace("T", " ")} · Generated by PatchGPT`,
    "",
    "## Patches in scope",
    "",
    "| KB | Title | Reboot | Highest CVSS | Actively exploited |",
    "|---|---|---|---|---|",
  ];
  for (const kb of content.kbs) {
    const p = db.prepare("SELECT * FROM patches WHERE kb = ?").get(kb) as Patch | undefined;
    if (!p) continue;
    const cves = getCvesForPatch(kb);
    const maxCvss = cves.reduce((m, c) => Math.max(m, c.cvss), 0);
    lines.push(
      `| ${kb} | ${p.title} | ${p.requires_reboot ? "required" : "not required"} | ${maxCvss ? maxCvss.toFixed(1) : "—"} | ${cves.some((c) => c.exploited) ? "**yes**" : "no"} |`
    );
  }

  lines.push("", "## Deployment rings", "");
  content.rings.forEach((ring, i) => {
    lines.push(`### Ring ${i + 1}: ${ring.name}`, "", `Window: **${ring.window}**`, "", "| Server | Role | Est. outage | Reboot risk |", "|---|---|---|---|");
    for (const id of ring.serverIds) {
      const s = byId.get(id);
      if (!s) continue;
      const impact = predictReboot(s);
      lines.push(`| ${s.name} | ${s.role} | ~${impact.estimatedMinutes} min | ${impact.risk} |`);
    }
    lines.push("");
  });

  lines.push("## AI rationale", "", content.rationale, "", `_Rationale generated by ${content.rationaleModel}._`);
  return { title: `Deployment report — ${plan.name}`, content: lines.join("\n") };
}
